### PR TITLE
Match upstream

### PR DESCRIPTION
**Pull request by gasche**
This PR updates the file in this repository to match the upstream version from Oleg.

I reviewed the change and believe that they improve efficiency and correctness.

If this PR is merged, there remain only a few files that differ at the repository root (see `meld delimcc/ caml-shift/`, for example):

- `META` has a different version (by the way, I updated the META from 201703 to 201803; it will match if you do a 2018.03 tag/release)
- `Makefile` is quite different: I have partially reviewed the change and it looked like there were good reasons for some of the differences, so I didn't touch this repository's Makefile. Ultimately we should discuss the changes with Oleg and try to converge to simplify maintenance.
- `README` is your readme, translated from Oleg's into markdown. Oleg did not change his README I think, so I did not update yours. (Again, we should think about converging to reduce differences.)
- I added an `opam` file to allow pinning from the directory sources. In the opam file, you ( @zinid ) are marked as the package maintainer (using your git-commit email).

### CODE REVIEW

**Comment by zinid** [comment]
Will you produce more commits, or shall I merge it?

**Comment by gasche** [comment]
I think this is a self-contained PR that you should feel free to merge, and I believe that making a release out of the resulting state would be fairly reasonable.

**Comment by gasche** [comment]
(I don't plan more commits in this PR unless you think that something should be changed.)

**Comment by zinid** [comment]
New tag `2018.03.04` is added.

**Pull request merged**
